# Specify a base image
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && apt-get install -y nodejs

#Install some dependencies

WORKDIR /usr/src/app
COPY . .
RUN npm install
EXPOSE 5000
# Set up a default conmmand
CMD [ "npm","start" ]